#!/bin/bash -xe

main() {
    echo 'Executing pre-chroot script'
    partition
    make_fs
    mount_fs
    (
        cd /mnt/gentoo
        unpack_base
        prep_chroot
    )
}

prep_chroot() {
    mount -t proc none proc
    mount --rbind /sys sys
    mount --rbind /dev dev
    cp /etc/resolv.conf etc
}

unpack_base() {
    local base_url='http://gentoo.mirrors.pair.com/releases/amd64/autobuilds'
    local build_path
    local build_file
    wget --no-verbose "${base_url}/latest-stage3-amd64-nomultilib.txt"
    build_path=$(grep -v '^#' latest-stage3-amd64-nomultilib.txt)
    build_path="${build_path%% *}"
    build_file="${build_path##*/}"

    wget --no-verbose "${base_url}/${build_path}.DIGESTS.asc"
    wget --no-verbose "${base_url}/${build_path}"

    gpg --import /autobuild_rsa.pub
    gpg --verify "${build_file}.DIGESTS.asc"
    sha512sum -c "${build_file}.DIGESTS.asc" ||
    sha256sum -c "${build_file}.DIGESTS.asc" ||
    sha1sum -c "${build_file}.DIGESTS.asc"
    
    tar -xv -f "$build_file"
}

partition() {
    echo 'Partitioning Filesystems'
    declare -i current=1
    parted -a opt -s /dev/sda -- "mklabel gpt"
    parted -a opt -s /dev/sda -- "mkpart BOOT ext4       $(( current ))  $(( current += 128   ))m"
    parted -a opt -s /dev/sda -- "mkpart SWAP linux-swap $(( current ))m $(( current += 4096  ))m"
    parted -a opt -s /dev/sda -- "mkpart ROOT ext4       $(( current ))m $(( current += 2048  ))m"
    parted -a opt -s /dev/sda -- "mkpart VAR  ext4       $(( current ))m $(( current += 8192  ))m"
    parted -a opt -s /dev/sda -- "mkpart USR  ext4       $(( current ))m $(( current += 12288 ))m"
    parted -a opt -s /dev/sda -- "mkpart TMP  ext4       $(( current ))m $(( current += 4096  ))m"
    parted -a opt -s /dev/sda -- "mkpart HOME ext4       $(( current )) -1"
}

make_fs() {
    echo 'Formatting Filesystems'
    echo /dev/sda[0-9]* | xargs -n1 -- mkfs -t ext4
}

mount_fs() {
    echo 'Mounting Filesystems in /mnt/gentoo'
    mkdir -p /mnt/gentoo
    mkswap /dev/sda2
    swapon /dev/sda2
    mount /dev/sda3 /mnt/gentoo/
    mkdir -p /mnt/gentoo/{boot,var,usr,tmp,home}
    mount /dev/sda1 /mnt/gentoo/boot
    mount /dev/sda4 /mnt/gentoo/var
    mount /dev/sda5 /mnt/gentoo/usr
    mount /dev/sda6 /mnt/gentoo/tmp
    mount /dev/sda7 /mnt/gentoo/home
}

main "$@"
sleep 10000
