#!/bin/sh -xe

main() {
    echo 'Executing post-chroot script'
    unmount_gentoo_root
    reboot
}
unmount_gentoo_root() {
    local dir
    for dir in boot dev home proc sys tmp usr var; do
        umount "/mnt/gentoo/$dir"
    done
    umount /mnt/gentoo
}
main "$@"
