#!/bin/bash -xe

main() {
  local snapshot_file='portage-latest.tar.xz'
  echo 'Preparing Chroot to Install Gentoo'
  cd /mnt/gentoo
  unpack
  prep
}

unpack() {
  echo 'Extracting Build Tarball (takes some time)'
  tar -xf build_tarball.tbz
  echo 'Extracting Portage Tarball (also takes some time)'
  tar -xf "$snapshot_file" -C '/mnt/gentoo/usr'
}

prep() {
  mount -t proc none proc
  mount --rbind /sys sys
  mount --rbind /dev dev
  cp /etc/resolv.conf etc
}

main "$@"
