#!/bin/bash -xe

main() {
    echo 'Preparing Filesystem to Install Gentoo'
    _partition
    _format
    _mount
}

_partition() {
    echo 'Partitioning Filesystems'
    declare -i current=1
    parted -a opt -s /dev/sda -- "mklabel gpt"
    parted -a opt -s /dev/sda -- "mkpart BOOT ext4       $(( current ))  $(( current += 128   ))m"
    parted -a opt -s /dev/sda -- "mkpart SWAP linux-swap $(( current ))m $(( current += 4096  ))m"
    parted -a opt -s /dev/sda -- "mkpart ROOT ext4       $(( current ))m $(( current += 2048  ))m"
    parted -a opt -s /dev/sda -- "mkpart VAR  ext4       $(( current ))m $(( current += 8192  ))m"
    parted -a opt -s /dev/sda -- "mkpart USR  ext4       $(( current ))m $(( current += 12288 ))m"
    parted -a opt -s /dev/sda -- "mkpart TMP  ext4       $(( current ))m $(( current += 4096  ))m"
    parted -a opt -s /dev/sda -- "mkpart HOME ext4       $(( current )) -1"
    parted -a opt -s /dev/sda -- "set 1 boot on"
}

_format() {
    echo 'Formatting Filesystems'
    echo /dev/sda[0-9]* | xargs -n1 -- mkfs -t ext4
}

_mount() {
    echo 'Mounting Filesystems in /mnt/gentoo'
    mkdir -p /mnt/gentoo
    mkswap /dev/sda2
    swapon /dev/sda2
    mount /dev/sda3 /mnt/gentoo/
    mkdir -p /mnt/gentoo/{boot,var,usr,tmp,home}
    mount /dev/sda1 /mnt/gentoo/boot
    mkdir -p /mnt/gentoo/boot/grub
    mount /dev/sda4 /mnt/gentoo/var
    mount /dev/sda5 /mnt/gentoo/usr
    mkdir -p /mnt/gentoo/usr/portage
    mount /dev/sda6 /mnt/gentoo/tmp
    mount /dev/sda7 /mnt/gentoo/home
}

main "$@"
