#!/bin/bash -xe

main() {
    echo 'Preparing Filesystem to Install Gentoo'
    _partition
    _format
    _mount
}

_partition() {
    echo 'Partitioning Filesystems'
    declare -i current=1
    parted -a opt -s /dev/sda -- "mklabel msdos"
    parted -a opt -s /dev/sda -- "mkpart primary  $(( current ))  $(( current += 128   ))m"
    parted -a opt -s /dev/sda -- "mkpart primary  $(( current ))m $(( current += 4096  ))m"
    parted -a opt -s /dev/sda -- "mkpart primary  $(( current ))m $(( current += 2048  ))m"
    parted -a opt -s /dev/sda -- "mkpart extended $(( current ))m -1"
    parted -a opt -s /dev/sda -- "mkpart logical  $(( current ))m $(( current += 8192  ))m"
    parted -a opt -s /dev/sda -- "mkpart logical  $(( current ))m $(( current += 12288 ))m"
    parted -a opt -s /dev/sda -- "mkpart logical  $(( current ))m $(( current += 4096  ))m"
    parted -a opt -s /dev/sda -- "mkpart logical  $(( current ))  -1"
}

_format() {
    echo 'Formatting Filesystems'
    echo /dev/sda{1,3,[5-8]} | xargs -n1 -- mkfs -t ext4
}

_mount() {
    echo 'Mounting Filesystems in /mnt/gentoo'
    mkdir -p /mnt/gentoo
    mkswap /dev/sda2
    swapon /dev/sda2
    mount /dev/sda3 /mnt/gentoo/
    mkdir -p /mnt/gentoo/{boot,var,usr,tmp,home}
    mount /dev/sda1 /mnt/gentoo/boot
    mkdir -p /mnt/gentoo/boot/grub
    mount /dev/sda5 /mnt/gentoo/var
    mount /dev/sda6 /mnt/gentoo/usr
    mkdir -p /mnt/gentoo/usr/portage
    mount /dev/sda7 /mnt/gentoo/tmp
    mount /dev/sda8 /mnt/gentoo/home
}

main "$@"
